name: GitHub Pages

on:
  push:
    branches:
      - master
  schedule:
    # Every Tuesday and Thursday at 05:00 UTC
    - cron: '0 5 * * 2,4'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          # hugo-version: '0.139.4'
          # extended: true
      
      - name: Restore Hugo cache
        uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod

      - name: Build
        env:
          HUGO_PARAMS_TWITTER: ${{ secrets.TWITTER_TOKEN }}
        run: hugo --minify --baseURL https://${{ vars.DOMAIN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: ${{ vars.DOMAIN }}
